//------------------------------------------------------------------------------
//   This code was generated by T4 template.
//   Any changes to this file may cause incorrect behavior and will be lost
//   when the code is regenerated.
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class PrefabHandler
{
    private static Dictionary<PrefabHandlerEnum, string> PrefabHandlerMapper = new Dictionary<PrefabHandlerEnum, string>()
    {
        {PrefabHandlerEnum.Prefab2, "Assets/Resources/samplePrefab.prefab"},
        {PrefabHandlerEnum.samplePrefab, "Assets/Resources/Prefab2.prefab"},
    };
    
    public int ResourceCount { get { return PrefabHandlerMapper.Count; }}

	/// <summary>
	/// Loads a game object from using its mapped enum
	/// </summary>
    public static GameObject Load(PrefabHandlerEnum resource)
    {
        return Load<GameObject>(resource);
    }

	/// <summary>
	/// Loads an asset from using its mapped enum
	/// </summary>    
    public static T Load<T>(PrefabHandlerEnum resource)
    {
        return AssetLoad<T>(PrefabHandlerMapper[resource]);
    }

	/// <summary>
	/// Load an asset using its path
	/// </summary>
    private static T AssetLoad<T>(string path)
    {
        var value = Resources.Load(path);
        return (T)Convert.ChangeType(value, typeof(T));
    }
    
	/// <summary>
	/// Enum indicating the available assets for loading using PrefabHandler load function
	/// </summary>
    public enum PrefabHandlerEnum
    {
        Prefab2,
        samplePrefab,
    }
}


