
// Make sure to set the customTool in the property panel of this file to "TextTemplatingFilePreprocessor"
// Make sure to set the customToolNamespace in the property panel of this file to "AutoAssetLoader.CodeGenerator"
//------------------------------------------------------------------------------
//   This code was generated by T4 template.
//   Any changes to this file may cause incorrect behavior and will be lost
//   when the code is regenerated.
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;
using AutoAssetLoader;
using System.ComponentModel;
using System.Collections.Generic;

namespace AutoAssetLoader
{
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum CS
		{
			[Description("c86cfc9044095dc48899bcc849419578")]
			RESOURCEHANDLERLOADTESTER,
			[Description("c7f853b295701bd45a974ba0d4b01971")]
			RESOURCEHANDLERBASE,
			[Description("64d9d42b62533bd42b2059c456d05324")]
			AUTOASSETLOADER,
			[Description("aed0edc28cf86ec48bb1b7f04195b9cb")]
			AUTOASSETLOADERMENU,
			[Description("3592623b4ec972b4c924376c9c662528")]
			RESOURCEHANDLERCODEGENERATOR,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum UNITY
		{
			[Description("770687bc95cf84a8592677afe579bfde")]
			SFD,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum PNG
		{
			[Description("e0358426410804918aa2e2d16a79f7dd")]
			BLOCK,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum PREFAB
		{
			[Description("4dee584f7d17347e4a049c078f4782be")]
			BLOCKPREFAB,
			[Description("6e8166ec00c8c4cb3aa459f4617de956")]
			SAMPLEPREFAB,
		}
	
}


