
// make sure the customTool in the perperty panel of this file is set to "TextTemplatingFilePreprocessor" unless it won't work
//------------------------------------------------------------------------------
//   This code was generated by T4 template.
//   Any changes to this file may cause incorrect behavior and will be lost
//   when the code is regenerated.
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;
using AutoAssetLoader;
using System.ComponentModel;
using System.Collections.Generic;

namespace AutoAssetLoader 
{
		/// <summary>
		/// Enum indicating the available assets for loading using _ResourHandler load function
		/// </summary>
		public enum _ResourHandlerEnum
		{
			[Description("4dee584f7d17347e4a049c078f4782be")]
			ITEM_PREFAB2,
			[Description("6e8166ec00c8c4cb3aa459f4617de956")]
			ITEM_SAMPLEPREFAB,
		}
}


