
// Make sure to set the customTool in the property panel of this file to "TextTemplatingFilePreprocessor"
// Make sure to set the customToolNamespace in the property panel of this file to "AutoAssetLoader.CodeGenerator"
//------------------------------------------------------------------------------
//   This code was generated by T4 template.
//   Any changes to this file may cause incorrect behavior and will be lost
//   when the code is regenerated.
//------------------------------------------------------------------------------

using System;
using UnityEditor;
using System.Linq;
using System.Reflection;
using System.ComponentModel;

namespace AutoAssetLoader
{
	public static class AutoLoader<T> where T : struct, IConvertible
    {
        static string GetEnumDescription(T value)
        {
            return value
                .GetType()
                .GetField(value.ToString())
                .GetCustomAttribute<DescriptionAttribute>(false)
                .Description;
        }

        public static bool ContainsGuid(string guid)
        {
            return typeof(T)
                .GetType()
                .GetCustomAttributes<DescriptionAttribute>()
                .Any((attribute) => attribute.Description == guid);
        }

        /// <summary>
        /// Loads a game object from using its mapped enum
        /// </summary>
        public static UnityEngine.GameObject Load(T resource)
        {
            return Load<UnityEngine.GameObject>(resource);
        }

        /// <summary>
        /// Loads an asset from using its mapped enum
        /// </summary>    
        public static G Load<G>(T resource)
        {
            return AssetLoad<G>(GetEnumDescription(resource));
        }

        /// <summary>
        /// Load an asset using its guid
        /// </summary>
        static G AssetLoad<G>(string guid)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var value = AssetDatabase.LoadAssetAtPath(path, typeof(G));
            return (G)Convert.ChangeType(value, typeof(G));
        }
    }

		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum SCENEASSET
		{
			[Description("770687bc95cf84a8592677afe579bfde")]
			SFD,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum DEFAULTASSET
		{
			[Description("4a91c20e9cc395544a37c4d9efa47531")]
			ASSETS_ASSETLOADERPLUGIN_RESOURCEHANDLERCODEGENERATOR,
			[Description("3bb3892128d5cfb43a60c1682b3d082f")]
			ASSETS_ASSETLOADERPLUGIN_EDITOR_RESOURCEHANDLERCODEGENERATOR_T4,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum MONOSCRIPT
		{
			[Description("64d9d42b62533bd42b2059c456d05324")]
			AUTOASSETLOADER,
			[Description("aed0edc28cf86ec48bb1b7f04195b9cb")]
			AUTOASSETLOADERMENU,
			[Description("5ae8db9e7a8b5a141b6678bee1f28acb")]
			ASSETS_ASSETLOADERPLUGIN_EDITOR_RESOURCEHANDLERCODEGENERATOR_CS,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum TEXTURE2D
		{
			[Description("e0358426410804918aa2e2d16a79f7dd")]
			BLOCK,
		}
		/// <summary>
		/// Enum indicating the available assets for loading using RessourceHandlerBase
		/// </summary>
		public enum GAMEOBJECT
		{
			[Description("4dee584f7d17347e4a049c078f4782be")]
			BLOCKPREFAB,
			[Description("6e8166ec00c8c4cb3aa459f4617de956")]
			SAMPLEPREFAB,
		}
	
}


